---
- name: Set AWS_PROFILE
  lineinfile:
    path: "/etc/environment"
    regexp: "^AWS_PROFILE="
    line: "AWS_PROFILE={{ aws_profile }}"

- name: Set IOW_BOUNDARY_TOOL_SETTINGS_BUCKET
  lineinfile:
    path: "/etc/environment"
    regexp: "^IOW_BOUNDARY_TOOL_SETTINGS_BUCKET="
    line: "IOW_BOUNDARY_TOOL_SETTINGS_BUCKET={{ iow-boundary-tool-development-config-us-east-1 }}"
