# Generated by Django 3.2.13 on 2022-09-16 18:59

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    Role = apps.get_model("api", "Role")
    db_alias = schema_editor.connection.alias
    Role.objects.using(db_alias).bulk_create([
        Role(description="ADMINISTRATOR"),
        Role(description="VALIDATOR"),
        Role(description="CONTRIBUTOR"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, migrations.RunPython.noop)
    ]
