# Generated by Django 3.2.13 on 2022-09-20 14:23

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwsid', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-78.6382, 35.7796), geography=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'utilities',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to='api.utility'),
        ),
    ]
