# Generated by Django 3.2.13 on 2022-09-29 22:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_utility'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', django.contrib.postgres.fields.citext.CICharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('options', models.JSONField(blank=True, help_text='This JSON dictionary contains state-specific configuration.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.State'),
        ),
    ]
