# Generated by Django 3.2.13 on 2022-09-29 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_utility_state_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.utility')),
            ],
            options={
                'verbose_name_plural': 'boundaries',
            },
        ),
    ]
