# Generated by Django 3.2.13 on 2022-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_has_admin_generated_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Contributor'), ('V', 'Validator'), ('A', 'Administrator')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
