# Generated by Django 3.2.13 on 2022-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_use_one_to_one_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
