# Generated by Django 3.2.13 on 2022-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_referenceimage_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='address_line_1',
            field=models.CharField(default='1 E Edenton St', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utility',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='utility',
            name='address_city',
            field=models.CharField(default='Raleigh', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utility',
            name='address_zip_code',
            field=models.CharField(default=27601, max_length=10),
            preserve_default=False,
        ),
    ]
