# Generated by Django 3.2.13 on 2022-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_utility_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(default='Job Title', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='(919) 733-4994', max_length=20),
            preserve_default=False,
        ),
    ]
