# Generated by Django 3.2.13 on 2022-10-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_additional_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='name',
            field=models.CharField(default='Test Boundary', max_length=127),
            preserve_default=False,
        ),
    ]
