# Generated by Django 3.2.13 on 2022-11-01 18:54

import api.models.submission
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_referenceimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.submission.shape_upload_path),
        ),
    ]
