# Generated by Django 3.2.13 on 2022-11-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_support_for_unapprovals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'get_latest_by': 'approved_at'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='approvals', to='api.submission'),
        ),
    ]
