#!/bin/bash

set -e

if [[ -n "${IOW_BOUNDARY_TOOL_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Build application for staging or a release.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ./scripts/fetch-data
        ./scripts/update

        # Build tagged container images
        GIT_COMMIT="${GIT_COMMIT}" docker buildx bake \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            --set django.cache-from="type=gha" \
            --set django.cache-to="type=gha,mode=max" \
            django

        # Test using tagged container images
        GIT_COMMIT="${GIT_COMMIT}" \
            ./scripts/test
    fi
fi
