#!/bin/bash

set -e

if [[ -n "${IOW_BOUNDARY_TOOL_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0") INPUT_GEOJSON_FILE

Ingests a given GeoJSON file into Vector Tiles.
Requires ogr2ogr and tippecanoe.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" = "--help" ]]; then
        usage
    else
        INPUT_GEOJSON_FILE=${1%%.*}

        ogr2ogr \
            -f GeoJSON "${INPUT_GEOJSON_FILE}_4326.geojson" \
            -t_srs EPSG:4326 \
            "$(basename -- "$1")"
        tippecanoe \
            --maximum-zoom=12 \
            --output-to-directory="${INPUT_GEOJSON_FILE}" \
            --layer="${INPUT_GEOJSON_FILE}" \
            --coalesce-densest-as-needed \
            --no-tile-compression \
            "${INPUT_GEOJSON_FILE}_4326.geojson"
    fi
fi
