#!/bin/bash

set -e

if [[ -n "${IOW_BOUNDARY_TOOL_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Run linters on the project's code
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint Bash scripts
        docker-compose \
            run --rm --no-deps shellcheck \
            scripts/*

        # Lint JavaScript
        docker-compose \
            run --rm --entrypoint ./node_modules/.bin/prettier \
            app --check src/

        docker-compose \
            run --rm --entrypoint ./node_modules/.bin/eslint \
            app src/ --ext .js --ext .jsx

        if [[ -n "${CI}" ]]; then
            # Lint Django app
            GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                -f docker-compose.yml \
                -f docker-compose.ci.yml \
                run --rm --no-deps --entrypoint flake8 django \
                --exclude settings.py,manage.py,*.pyc,api/migrations/*

            GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                -f docker-compose.yml \
                -f docker-compose.ci.yml \
                run --rm --no-deps --entrypoint black django \
                --skip-string-normalization --check --diff \
                --extend-exclude migrations .

            GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                -f docker-compose.yml \
                -f docker-compose.ci.yml \
                run --rm --entrypoint python django \
                manage.py makemigrations --check
        else
            # Lint Django app
            docker-compose \
                run --rm --no-deps --entrypoint flake8 django \
                --exclude settings.py,manage.py,*.pyc,api/migrations/*

            docker-compose \
                run --rm --no-deps --entrypoint isort django . --check

            docker-compose \
                run --rm --no-deps --entrypoint black django \
                --skip-string-normalization --check --diff \
                --extend-exclude migrations .

            docker-compose \
                run --rm --entrypoint python django \
                manage.py makemigrations --check --dry-run
        fi
    fi
fi
