#!/bin/bash

set -e

if [[ -n "${PROJECT_NAME_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Bring up all of the services required for the project to function.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" = "--help" ]]; then
        usage
    else
        docker-compose up app
    fi
fi
