#!/bin/bash

set -e

if [[ -n "${IOW_BOUNDARY_TOOL_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Build container images.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Ensure container images are current
        docker-compose build

        # Update Yarn dependencies
        docker-compose \
            run --rm --no-deps app \
            bun install --frozen-lockfile

        # Build static asset bundle for React frontend
        docker-compose \
            run --rm --no-deps app \
            bun run build

        # Bring up PostgreSQL and Django in a way that respects
        # configured service health checks.
        docker-compose up -d database django

        # Apply any outstanding Django migrations
        ./scripts/manage migrate

        # Collect Django static files
        ./scripts/manage collectstatic --no-input
    fi
fi
