#!/bin/bash

set -e

if [[ -n "${IOW_BOUNDARY_TOOL_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute Yarn CLI commands.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose \
            run --rm --no-deps --entrypoint "bash -c" app \
            "yarn ${*:1}"
    fi
fi
