---
- hosts: all
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "iow-boundary-tool.devtools" }
    - { role: "iow-boundary-tool.docker" }
    - { role: "iow-boundary-tool.environment" }
